image: alpine

variables:
  DEFECTDOJO_URL: "http://host.docker.internal:8080/api/v2"
  DEFECTDOJO_TOKEN: "5351a7773fbe13cf73378d6ba2c85a789596d7ef"
  DEFECTDOJO_SCAN_MINIMUM_SEVERITY: "Info"
  DEFECTDOJO_SCAN_ACTIVE: "true"
  DEFECTDOJO_SCAN_VERIFIED: "true"
  DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS: "true"
  DEFECTDOJO_SCAN_ENVIRONMENT: "Default"
  DEFECTDOJO_SCAN_TYPE: "Trivy Scan"
  DEFECTDOJO_ENGAGEMENTID: "6"
  DEFECTDOJO_SCAN_FILE: "results.json"

before_script:
    - apk add --no-cache curl jq coreutils
    - TODAY=$(date +%Y-%m-%d)

defectdojo_upload_results:
  stage: .post
  allow_failure: false
  script:
    - >
      curl --request POST "${DEFECTDOJO_URL}/import-scan/" \
            --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            --form "scan_date=\"${TODAY}\"" \
            --form "minimum_severity=\"${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}\"" \
            --form "active=\"${DEFECTDOJO_SCAN_ACTIVE}\"" \
            --form "verified=\"${DEFECTDOJO_SCAN_VERIFIED}\"" \
            --form "scan_type=\"${DEFECTDOJO_SCAN_TYPE}\"" \
            --form "engagement=\"${DEFECTDOJO_ENGAGEMENTID}\"" \
            --form "file=@${DEFECTDOJO_SCAN_FILE}" \
            --form "close_old_findings=\"${DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS}\"" \
            --form "environment=\"${DEFECTDOJO_SCAN_ENVIRONMENT}\""
