image: alpine

stages:
  - trivy_scan
  - upload_results

variables:
  DEFECTDOJO_URL: "http://host.docker.internal:8080/api/v2"
  DEFECTDOJO_TOKEN: "5351a7773fbe13cf73378d6ba2c85a789596d7ef"
  DEFECTDOJO_SCAN_MINIMUM_SEVERITY: "Info"
  DEFECTDOJO_SCAN_ACTIVE: "true"
  DEFECTDOJO_SCAN_VERIFIED: "true"
  DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS: "true"
  DEFECTDOJO_SCAN_ENVIRONMENT: "Default"
  DEFECTDOJO_SCAN_FILE_NAME: "gl-container-scanning-report.json"
  DEFECTDOJO_SCAN_DIRECTORY: "./scanresults/${DEFECTDOJO_SCAN_FILE_NAME}"

before_script:
  - apk add --update --no-cache curl jq coreutils findutils
  - TODAY=$(date +%Y-%m-%d)

prepare:
  stage: .pre
  script:
    - echo "Prepare create directory and load environment file"
    - source ./scripts/command_script.sh
    - mkdir -p ./scanresults/trivy
    - load_file
  cache:
    key: defectdojo
    paths:
      - defectdojo-infrastructure.env

trivy_scan:
  stage: trivy_scan
  image: docker:stable
  before_script:
    - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    - echo $TRIVY_VERSION
    - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""
    DEFECTDOJO_SCAN_FILE_NAME: "trivy-container-scanning-report.json"
    DEFECTDOJO_SCAN_FILE_DIRECTORY: "./scanresults/trivy"
  allow_failure: false
  script:
    - ./trivy image -f json -o "${DEFECTDOJO_SCAN_FILE_DIRECTORY}/${DEFECTDOJO_SCAN_FILE_NAME}" ghcr.io/domehahn/api-gateway:latest
  cache:
    paths:
      - .trivycache/
  artifacts:
    paths:
      - scanresults/trivy/trivy-container-scanning-report.json

defectdojo_upload_trivy_results:
  stage: upload_results
  allow_failure: false
  variables:
    DEFECTDOJO_SCAN_FILE_DIRECTORY: "./scanresults/trivy/trivy-container-scanning-report.json"
  script:
    - source defectdojo-infrastructure.env
    - >
      curl --request POST "${DEFECTDOJO_URL}/import-scan/" \
         --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
         --form "scan_date=\"${TODAY}\"" \
         --form "minimum_severity=\"${DEFECTDOJO_SCAN_MINIMUM_SEVERITY}\"" \
         --form "active=\"${DEFECTDOJO_SCAN_ACTIVE}\"" \
         --form "verified=\"${DEFECTDOJO_SCAN_VERIFIED}\"" \
         --form "scan_type=\"Trivy Scan\"" \
         --form "engagement=\"${DEFECTDOJO_ENGAGEMENT_ID}\"" \
         --form "file=@${DEFECTDOJO_SCAN_FILE_DIRECTORY}" \
         --form "close_old_findings=\"${DEFECTDOJO_SCAN_CLOSE_OLD_FINDINGS}\"" \
         --form "environment=\"${DEFECTDOJO_SCAN_ENVIRONMENT}\""
  artifacts:
    paths:
      - defectdojo-infrastructure.env