image: alpine

before_script:
    - apk add --no-cache curl jq coreutils
    - TODAY=$(date +%Y-%m-%d)
    - ENDDAY=$(date +%Y-%m-%d)

variables:
  DEFECTDOJO_ENGAGEMENT_PERIOD: 7
  DEFECTDOJO_ENGAGEMENT_STATUS: "Not Started"
  DEFECTDOJO_ENGAGEMENT_BUILD_SERVER: "null"
  DEFECTDOJO_ENGAGEMENT_SOURCE_CODE_MANAGEMENT_SERVER: "null"
  DEFECTDOJO_ENGAGEMENT_ORCHESTRATION_ENGINE: "null"
  DEFECTDOJO_ENGAGEMENT_DEDUPLICATION_ON_ENGAGEMENT: "false"
  DEFECTDOJO_ENGAGEMENT_THREAT_MODEL: "true"
  DEFECTDOJO_ENGAGEMENT_API_TEST: "true"
  DEFECTDOJO_ENGAGEMENT_PEN_TEST: "true"
  DEFECTDOJO_ENGAGEMENT_CHECK_LIST: "true"
  DEFECTDOJO_NOT_ON_MASTER: "false"
  DEFECTDOJO_ANCHORE_DISABLE: "false"
  DEFECTDOJO_URL: "http://host.docker.internal:8080/api/v2"
  DEFECTDOJO_TOKEN: "5351a7773fbe13cf73378d6ba2c85a789596d7ef"
  DEFECTDOJO_PRODUCTID: "1"

defectdojo_create_infrastructure:
  stage: .pre
  variables:
    GIT_STRATEGY: none
  allow_failure: false
  script:
    - >
      USER_ID=$(curl --request POST "${DEFECTDOJO_URL}/users/" \
        --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "username": "Gitlab",
          "first_name": "CI",
          "last_name": "CD",
          "email": "dominik.hahn@opitz-consulting.com",
          "is_active": true,
          "is_superuser": true,
          "password": "Sup3rS4f3P4$$w0rd",
          "configuration_permissions": [
            285
          ]
        }' | jq -r '.id')
    - >
      PRODUCT_TYPE_ID=$(curl --request POST "${DEFECTDOJO_URL}/product_types/" \
        --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "name": "Security",
          "description": "Product for Security",
          "critical_product": true,
          "key_product": true
        }' | jq -r '.id')
    - >
      curl --request POST "${DEFECTDOJO_URL}/product_type_members/" \
        --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
        --header 'Content-Type: application/json' \
        --data-raw "{
          \"product_type\": \"${PRODUCT_TYPE_ID}\",
          \"user\": \"${USER_ID}\",
          \"role\": 4
        }"
    - >
      PRODUCT_ID=$(curl --request POST "${DEFECTDOJO_URL}/products/" \
        --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
        --header 'Content-Type: application/json' \
        --data-raw "{
          \"name\": \"Spring Cloud API-Gateway\",
          \"description\": \"A API-Gateway created by Spring Cloud.\",
          \"prod_numeric_grade\": 2147483647,
          \"business_criticality\": \"very high\",
          \"platform\": \"web service\",
          \"lifecycle\": \"construction\",
          \"origin\": \"third party library\",
          \"user_records\": 2147483647,
          \"revenue\": \"-458\",
          \"external_audience\": true,
          \"internet_accessible\": true,
          \"enable_product_tag_inheritance\": true,
          \"enable_simple_risk_acceptance\": true,
          \"enable_full_risk_acceptance\": true,
          \"disable_sla_breach_notifications\": true,
          \"product_manager\": \"${USER_ID}\",
          \"technical_contact\": \"${USER_ID}\",
          \"team_manager\": \"${USER_ID}\",
          \"prod_type\": \"${PRODUCT_TYPE_ID}\",
          \"sla_configuration\": 1,
          \"regulations\": [
            13
          ]
        }" | jq -r '.id')
    - >
      curl --request POST "${DEFECTDOJO_URL}/engagements/" \
        --header "Authorization: Token ${DEFECTDOJO_TOKEN}" \
        --header 'Content-Type: application/json' \
        --data-raw "{
          \"name\": \"Trivy Scan\",
          \"description\": \"Trivy Scan result\",
          \"version\": \"1.0\",
          \"first_contacted\": \"${TODAY}\",
          \"target_start\": \"${TODAY}\",
          \"target_end\": \"${ENDDAY}\",
          \"lead\": \"${USER_ID}\",
          \"engagement_type\": \"CI/CD\",
          \"product\": \"${PRODUCT_ID}\"
        }"