---
- name: Load variable file, or a default if not found.
  include_vars: "main.yml"
  
- name: Create S3FS credentials file
  copy:
    dest: /etc/passwd-s3fs
    content: "{{ item.accessKeyId }}:{{ item.secretAccessKey }}"
    mode: '0600'
  with_items: "{{ s3fs.buckets }}"

- name: Ensure mountpoints directory exists
  file:
    path: "{{ item.mountpoint }}"
    state: directory
    mode: '0755'
  with_items: "{{ s3fs.buckets }}"

- name: Make sure mountpoints are present in fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ item.bucket }} /opt/s3fs/bucket fuse.s3fs _netdev,allow_other,url={{ item.url }},use_path_request_style,passwd_file={{ s3fs.passwd_file }} 0 0"
    create: yes
  with_items: "{{ s3fs.buckets }}"