---
# vars file for domehahn.s3fs-fuse
s3fs:
  source: https://github.com/s3fs-fuse/s3fs-fuse.git
  passwd_file: /etc/passwd-s3fs
  daemon: /usr/local/bin/s3fs
  add_to_fstab: True
  buckets:
    - mountpoint: "{{ ansible_env.S3FS_MOUNT | default('/opt/s3fs/bucket') }}"
      bucket: "{{ ansible_env.S3FS_BUCKET | default('s3fs-bucket') }}"
      accessKeyId: "{{ ansible_env.S3FS_ACCESS_KEY_ID | default('accessKeyId') }}"
      secretAccessKey: "{{ ansible_env.S3FS_SECRET_ACCESS_KEY | default('secretAccessKey') }}"
      url: "{{ ansible_env.S3FS_BUCKET_URL | default('http://s3.amazonaws.com') }}"
      args: "{{ ansible_env.S3FS_ARGS | default('') }}"